# This file configures the Netlify build environment.

[build]
  # Specifies the command to build the project.
  command = "npm run build"
  
  # Specifies the directory that contains the built project.
  publish = "dist"

[build.environment]
  # Sets the Node.js version for the build, resolving dependency issues.
  NODE_VERSION = "20"

# This rule ensures that client-side routing works correctly for this Single Page App (SPA).
# It redirects all requests to the main index.html file, allowing React Router to handle them.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
